version: 0.1
os: linux
files:
  - source: /
    destination: /home/ubuntu/trident

hooks:

  BeforeInstall:
    - location: deployment_scripts/install_requirements.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deployment_scripts/deploy.sh
      timeout: 300
      runas: root